Update

diff --git a/common/bin/system-setting b/common/bin/system-setting
--- a/common/bin/system-setting
+++ b/common/bin/system-setting
@@ -20,7 +20,7 @@ _run() {
     command -v "$1" >/dev/null 2>&1 && "$@"
 }
 
-if [ $# -lt 2 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then
+if [ $# -lt 2 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
     echo "Usage: $(basename $0) SETTING CHANGE"
     echo "Make a CHANGE to a system SETTING."
     echo "Examples:"
@@ -40,15 +40,15 @@ notify-send-volume() {
     case $1 in
         mute)
             _run notify-send --expire-time=${EXPIRE_TIME} --replace-id=${REPLACE_ID} --icon="volume-$1" "Muted"
-            ;;
+           ;;
 
         unmute)
             _run notify-send --expire-time=${EXPIRE_TIME} --replace-id=${REPLACE_ID} --hint=int:value:"${volume}" --icon="volume-$1" "Unmuted"
-            ;;
+           ;;
 
         *)
             _run notify-send --expire-time=${EXPIRE_TIME} --replace-id=${REPLACE_ID} --hint=int:value:"${volume}" --icon="volume-$1" "Volume $1"
-            ;;
+           ;;
     esac
 }
 
@@ -59,68 +59,68 @@ notify-send-brightness() {
 
 case $1 in
     volume)
-        _command pamixer || (echo "Missing pamixer command" ; exit 1)
+        _command pamixer || (echo "Missing pamixer command"; exit 1)
         case $2 in
             up)
                 pamixer --unmute
                 pamixer --increase 5 --allow-boost
                 notify-send-volume $2
-                ;;
+               ;;
 
             down)
                 pamixer --unmute
                 pamixer --decrease 5 --allow-boost
                 notify-send-volume $2
-                ;;
+               ;;
 
             mute)
                 pamixer --mute
                 notify-send-volume $2
-                ;;
+               ;;
 
             unmute)
                 pamixer --unmute
                 notify-send-volume $2
-                ;;
+               ;;
 
             toggle-mute)
                 pamixer --toggle-mute
-                if $(pamixer --get-mute) ; then
+                if $(pamixer --get-mute); then
                     notify-send-volume mute
                 else
                     notify-send-volume unmute
                 fi
-                ;;
+               ;;
         esac
-        ;;
+       ;;
 
     brightness)
-        _command light || (echo "Missing light command" ; exit 1)
+        _command light || (echo "Missing light command"; exit 1)
         case $2 in
             up)
                 light -A 2
                 notify-send-brightness $2
-                ;;
+               ;;
 
             down)
                 light -U 2
                 notify-send-brightness $2
-                ;;
+               ;;
         esac
-        ;;
+       ;;
 
     display)
-        _command xrandr || (echo "Missing xrandr command" ; exit 1)
+        _command xrandr || (echo "Missing xrandr command"; exit 1)
         case $2 in
             toggle)
-                if $(xrandr --listactivemonitors | grep -q "^Monitors: 1$") ; then
+                if $(xrandr --listactivemonitors | grep -q "^Monitors: 1$"); then
                     xrandr --output HDMI-1-0 --auto
                 else
                     xrandr --output HDMI-1-0 --off
                 fi
-                ;;
+               ;;
         esac
-        ;;
+       ;;
 esac
 
 #===============================================================================
